# Generated by Django 5.0.4 on 2024-04-30 09:37

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('Descriptio', models.TextField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='0-Show, 1-Hidden')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Vendor', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('Original_Price', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('Produt_image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('Descriptio', models.TextField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='0-Show, 1-Hidden')),
                ('Trending', models.BooleanField(default=False, help_text='0-default, 1-Trending')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catagory')),
            ],
        ),
    ]
